### ISSUE TITLE
System.Runtime.InteropServices.COMException

### ISSUE THREAD

**Issue by wstaelens** [vinaypamnani/wmie2#16]
For **ROOT\CIMV2** on Classes (1355) I had **Win32_Process** i had selected "Methods (7)" tab active.

I selected "GetOwner" method, focus was on **User** in the Out Params.
I clicked on the bing.com url in the info pane at the bottom:

> Search Online Documentation:
> http://www.bing.com/search?q=GetOwner+Method+of+the+Win32_Process+Class

which resulted in an exception: (can't reproduce)

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
>    at System.Windows.Forms.UnsafeNativeMethods.ITextRange.ScrollIntoView(Int32 value)
>    at System.Windows.Forms.TextBoxBase.ScrollToCaret()
>    at WmiExplorer.WmiExplorer.richTextBox_Click(Object sender, EventArgs e)
>    at System.Windows.Forms.Control.OnClick(EventArgs e)
>    at System.Windows.Forms.TextBoxBase.OnMouseUp(MouseEventArgs mevent)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.RichTextBox.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
> ----------------------------------------
> WmiExplorer
>     Assembly Version: 2.0.0.2
>     Win32 Version: 2.0.0.2
>     CodeBase: file:///C:/Users/wst.WINKING/Downloads/WmiExplorer_2.0.0.2/WmiExplorer.exe
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.3752.0 built by: NET48REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.3752.0 built by: NET48REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.3752.0 built by: NET48REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> Accessibility
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.3752.0 built by: NET48REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
> ----------------------------------------
> System.Management
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.3752.0 built by: NET48REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
> ----------------------------------------
> System.Runtime.Caching
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.3752.0
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Caching/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Caching.dll
> ----------------------------------------
> Microsoft.GeneratedCode
>     Assembly Version: 1.0.0.0
>     Win32 Version: 4.8.3752.0 built by: NET48REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> Microsoft.GeneratedCode
>     Assembly Version: 1.0.0.0
>     Win32 Version: 4.8.3752.0 built by: NET48REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> System.Data
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
> ----------------------------------------
> System.Numerics
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.3752.0 built by: NET48REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.
>

**Comment by chrislogan2** [comment]
I can reproduce this, I'll look at it at some point this week. this is fairly specific and simple to reproduce so troubleshooting the project should be relatively easy.

**Comment by vinaypamnani** [comment]
Try the new version https://github.com/vinaypamnani/wmie, and see if the issue still persists
