### ISSUE TITLE
Dell WMI crash 

### ISSUE THREAD

**Issue by KONIKPK** [vinaypamnani/wmie2#19]
We have extended WMi for Dell DCIM.
In some classes WMIexplorer crash. 

![image](https://user-images.githubusercontent.com/10882733/108512795-051de800-72c2-11eb-8beb-f7a60781356b.png)

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at WmiExplorer.WmiExplorer.GetPropertyHelp(PropertyData property, Boolean& enumAvailable, String& propertyHelp)
   at WmiExplorer.WmiExplorer.PopulateClassProperties(WmiClass wmiClass)
   at WmiExplorer.WmiExplorer.listClasses_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ListView.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by vinaypamnani** [comment]
Try the new version https://github.com/vinaypamnani/wmie, and see if the issue still persists
